---
- name: Configure webserver
  hosts: all
  sudo: True
  tasks:
    - name: copy h2o file
      copy: src=/home/ubuntu/github/h2o_ec2/h2o-3/ec2/h2o-3.8.2.11.zip dest=/home/ec2-user/ owner=ec2-user
    - name: Create folder
      file: path=/ec2-user/.aws state=directory owner=ec2-user
